#
# Note
#   Travis CI will update GitHub Pages
#

notifications:
  email:
    - luncliff@gmail.com

os: linux
dist: bionic

addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
      - sourceline: "deb https://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main"
        key_url: "https://apt.llvm.org/llvm-snapshot.gpg.key"
    packages:
      - tree
      - clang-9
      - g++-9

language: python
python:
  - "3.7"

install:
  - pip install -r requirements.txt

script:
  - mkdocs build

deploy:
  - provider: pages
    github_token: ${MAINTAINER_GITHUB_TOKEN}
    local_dir: _site
    skip_cleanup: true
    keep_history: true
    on:
      branch: master
